// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `ComplexData.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ComplexData;

public abstract class Callback_IMyData_getDataList
    extends IceInternal.TwowayCallback implements Ice.TwowayCallbackArg1<ComplexData.DataInfo[]>
{
    public final void __completed(Ice.AsyncResult __result)
    {
        IMyDataPrxHelper.__getDataList_completed(this, __result);
    }
}
