// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `ComplexData.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ComplexData;

public final class DataInfoHolder extends Ice.Holder<DataInfo>
{
    public
    DataInfoHolder()
    {
    }

    public
    DataInfoHolder(DataInfo value)
    {
        super(value);
    }
}
