// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `ComplexData.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ComplexData;

public class DataInfo implements java.lang.Cloneable, java.io.Serializable
{
    public String age;

    public String name;

    public String score;

    public DataInfo()
    {
        age = "";
        name = "";
        score = "";
    }

    public DataInfo(String age, String name, String score)
    {
        this.age = age;
        this.name = name;
        this.score = score;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        DataInfo _r = null;
        if(rhs instanceof DataInfo)
        {
            _r = (DataInfo)rhs;
        }

        if(_r != null)
        {
            if(age != _r.age)
            {
                if(age == null || _r.age == null || !age.equals(_r.age))
                {
                    return false;
                }
            }
            if(name != _r.name)
            {
                if(name == null || _r.name == null || !name.equals(_r.name))
                {
                    return false;
                }
            }
            if(score != _r.score)
            {
                if(score == null || _r.score == null || !score.equals(_r.score))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::ComplexData::DataInfo");
        __h = IceInternal.HashUtil.hashAdd(__h, age);
        __h = IceInternal.HashUtil.hashAdd(__h, name);
        __h = IceInternal.HashUtil.hashAdd(__h, score);
        return __h;
    }

    public DataInfo
    clone()
    {
        DataInfo c = null;
        try
        {
            c = (DataInfo)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeString(age);
        __os.writeString(name);
        __os.writeString(score);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        age = __is.readString();
        name = __is.readString();
        score = __is.readString();
    }

    static public void
    __write(IceInternal.BasicStream __os, DataInfo __v)
    {
        if(__v == null)
        {
            __nullMarshalValue.__write(__os);
        }
        else
        {
            __v.__write(__os);
        }
    }

    static public DataInfo
    __read(IceInternal.BasicStream __is, DataInfo __v)
    {
        if(__v == null)
        {
             __v = new DataInfo();
        }
        __v.__read(__is);
        return __v;
    }
    
    private static final DataInfo __nullMarshalValue = new DataInfo();

    public static final long serialVersionUID = -1449073042L;
}
