// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `ComplexData.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ComplexData;

public interface IMyData extends Ice.Object,
                                 _IMyDataOperations, _IMyDataOperationsNC
{
    public static final String ice_staticId = "::ComplexData::IMyData";

    public static final long serialVersionUID = 897397344L;
}
